
POST http://localhost:3000/login
Content-Type: application/json

{
    "eMail" : "homer.simpson.4@societe.com",
    "password" :"Aaaaaaaa1*"
}

###

GET http://localhost:3000/home_page
Content-Type: application/json

{
    "eMail" : "homer.simpson.4@societe.com"
}

###

POST http://localhost:3000/create
Content-Type: application/json

{
    "create_team" : false,
    "firstName" : "Homer",
    "lastName" :"Simpson",
    "password" :"Homer2*",
    "passwordConfirm" : "Homer2*",
    "dept" : "Finance",
    "numberTeam" : 2
}

###

GET http://localhost:3000/find
Content-Type: application/json

{
    "dept": "business"
}

###

GET http://localhost:3000/find
Content-Type: application/json

{
    "name" : "lisa simpson",
    "dept" :"business"
}

###

GET http://localhost:3000/find
Content-Type: application/json

{
    "dept" :"business",
    "number" : 1
}

###

GET http://localhost:3000/find
Content-Type: application/json

{
    "name" : "lisa simpson",
    "dept" :"business",
    "number" : 1
}

###

GET http://localhost:3000/chat
Content-Type: application/json

{
    "myMail" : "lisa.simpson@societe.com",
    "yourMail" : "bart.simpson@societe.com"
}

###

POST http://localhost:3000/chat
Content-Type: application/json

{
    "senderMail" : "bart.simpson@societe.com",
    "recipientMail" : "lisa.simpson@societe.com",
    "content" : "Tres bien merci"
}

###

POST http://localhost:3000/profile
Content-Type: application/json

{
    "eMail" : "homer.simpson.4@societe.com",
    "oldPassword" : "Bbbbbbb1*",
    "password" : "Aaaaaaaa1*",
    "passwordConfirm" : "Aaaaaaaa1*"
}